// flow-typed signature: 066bdce824eb39bffb6bf5c67edb47f3
// flow-typed version: <<STUB>>/dentist_v1.0.3/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dentist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dentist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dentist/dist' {
  declare module.exports: any;
}

declare module 'dentist/src' {
  declare module.exports: any;
}

declare module 'dentist/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dentist/dist/index' {
  declare module.exports: $Exports<'dentist/dist'>;
}
declare module 'dentist/dist/index.js' {
  declare module.exports: $Exports<'dentist/dist'>;
}
declare module 'dentist/src/index' {
  declare module.exports: $Exports<'dentist/src'>;
}
declare module 'dentist/src/index.js' {
  declare module.exports: $Exports<'dentist/src'>;
}
declare module 'dentist/test/index' {
  declare module.exports: $Exports<'dentist/test'>;
}
declare module 'dentist/test/index.js' {
  declare module.exports: $Exports<'dentist/test'>;
}
