// flow-typed signature: b21e477e3461659d1ee034726291b6fe
// flow-typed version: <<STUB>>/tree-sitter_v0.15.8/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tree-sitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tree-sitter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'tree-sitter/index' {
  declare module.exports: $Exports<'tree-sitter'>;
}
declare module 'tree-sitter/index.js' {
  declare module.exports: $Exports<'tree-sitter'>;
}
