// flow-typed signature: 809c39549146a25ed50538001aaef8fc
// flow-typed version: <<STUB>>/tree-sitter-go_v0.15.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tree-sitter-go'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tree-sitter-go' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tree-sitter-go/grammar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tree-sitter-go/grammar.js' {
  declare module.exports: $Exports<'tree-sitter-go/grammar'>;
}
declare module 'tree-sitter-go/index' {
  declare module.exports: $Exports<'tree-sitter-go'>;
}
declare module 'tree-sitter-go/index.js' {
  declare module.exports: $Exports<'tree-sitter-go'>;
}
